<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Monitoring Report</title>

    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            color: #111827;
            margin: 32px;
            font-size: 13px;
            line-height: 1.5;
        }

        .no-print {
            margin-bottom: 20px;
        }

        .no-print a,
        .no-print button {
            display: inline-block;
            padding: 8px 12px;
            border: 1px solid #111827;
            border-radius: 4px;
            text-decoration: none;
            color: #111827;
            background: white;
            cursor: pointer;
            font-size: 13px;
            margin-right: 6px;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #111827;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .header .agency {
            font-weight: bold;
            font-size: 15px;
            text-transform: uppercase;
        }

        .header .office {
            font-size: 13px;
            margin-top: 2px;
        }

        .header .title {
            margin-top: 12px;
            font-size: 18px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .meta {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 8px 24px;
            margin-bottom: 16px;
        }

        .notice {
            border: 1px solid #92400e;
            background: #fffbeb;
            color: #78350f;
            padding: 10px 12px;
            margin-bottom: 18px;
            font-size: 12px;
        }

        .section {
            margin-top: 18px;
            page-break-inside: avoid;
        }

        .section h2 {
            font-size: 14px;
            text-transform: uppercase;
            border-bottom: 1px solid #9ca3af;
            padding-bottom: 4px;
            margin-bottom: 8px;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 12px;
        }

        .summary-card {
            border: 1px solid #d1d5db;
            padding: 10px;
        }

        .summary-card .label {
            font-size: 11px;
            color: #4b5563;
            text-transform: uppercase;
        }

        .summary-card .value {
            font-size: 18px;
            font-weight: bold;
            margin-top: 4px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 6px;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 6px 8px;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            text-align: left;
            font-weight: bold;
        }

        .footer {
            margin-top: 32px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 32px;
        }

        .signature-line {
            margin-top: 42px;
            border-top: 1px solid #111827;
            padding-top: 4px;
            text-align: center;
        }

        .small {
            font-size: 11px;
            color: #4b5563;
        }

        @media print {
            body {
                margin: 18mm;
            }

            .no-print {
                display: none;
            }

            a {
                color: #111827;
                text-decoration: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print">
        <a href="{{ route('staff.reports.monitoring.index') }}">Back to Monitoring Dashboard</a>
        <button onclick="window.print()">Print / Save as PDF</button>
    </div>

    <div class="header">
        <div class="agency">Department of Agrarian Reform</div>
        <div class="office">Negros Oriental Provincial Office</div>
        <div class="office">Land Transfer Clearance and Monitoring System</div>

        <div class="title">Monitoring Report</div>
    </div>

    <div class="meta">
        <div>
            <strong>Date Generated:</strong>
            {{ $generatedAt?->timezone('Asia/Manila')->format('F d, Y h:i A') }}
        </div>

        <div>
            <strong>Generated By:</strong>
            {{ $generatedBy?->name ?? 'System User' }}
        </div>

        <div>
            <strong>Report Type:</strong>
            Clearance Application Monitoring Summary
        </div>

        <div>
            <strong>System Scope:</strong>
            Administrative processing and monitoring
        </div>
    </div>

    <div class="notice">
        <strong>Scope Notice:</strong>
        {{ $scopeNotice }}
    </div>

    <div class="section">
        <h2>Summary</h2>

        <div class="summary-grid">
            <div class="summary-card">
                <div class="label">Total Applications</div>
                <div class="value">{{ $totalApplications }}</div>
            </div>

            <div class="summary-card">
                <div class="label">Total Clearances</div>
                <div class="value">{{ $totalClearances }}</div>
            </div>

            <div class="summary-card">
                <div class="label">Total Clearance Area</div>
                <div class="value">{{ number_format((float) $totalClearanceArea, 2) }}</div>
                <div class="small">hectares</div>
            </div>

            <div class="summary-card">
                <div class="label">Municipalities Covered</div>
                <div class="value">{{ $municipalityBreakdown->count() }}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Application Status Breakdown</h2>

        <table>
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($statusCounts as $status => $total)
                    <tr>
                        <td>{{ ucwords(str_replace('_', ' ', $status)) }}</td>
                        <td>{{ $total }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2">No application status records found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Clearance Decision Breakdown</h2>

        <table>
            <thead>
                <tr>
                    <th>Decision Status</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($clearanceCounts as $decisionStatus => $total)
                    <tr>
                        <td>{{ ucwords(str_replace('_', ' ', $decisionStatus)) }}</td>
                        <td>{{ $total }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2">No clearance decision records found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Municipality Breakdown</h2>

        <table>
            <thead>
                <tr>
                    <th>Municipality</th>
                    <th>Total Applications</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($municipalityBreakdown as $row)
                    <tr>
                        <td>{{ $row->municipality }}</td>
                        <td>{{ $row->total }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2">No municipality records found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Recent Applications</h2>

        <table>
            <thead>
                <tr>
                    <th>Application Code</th>
                    <th>Transferor</th>
                    <th>Transferee</th>
                    <th>Status</th>
                    <th>Location</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($recentApplications as $application)
                    <tr>
                        <td>{{ $application->application_code }}</td>
                        <td>{{ $application->transferor_name ?? 'N/A' }}</td>
                        <td>{{ $application->transferee_name ?? 'N/A' }}</td>
                        <td>{{ ucwords(str_replace('_', ' ', $application->status)) }}</td>
                        <td>{{ $application->barangay ?? 'N/A' }}, {{ $application->municipality ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">No recent applications found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Recent Clearance Outputs</h2>

        <table>
            <thead>
                <tr>
                    <th>Clearance No.</th>
                    <th>Decision</th>
                    <th>Total Area</th>
                    <th>Generated At</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($recentClearances as $clearance)
                    <tr>
                        <td>{{ $clearance->clearance_number ?? 'N/A' }}</td>
                        <td>{{ ucwords(str_replace('_', ' ', $clearance->decision_status)) }}</td>
                        <td>{{ number_format((float) $clearance->total_area_hectares, 2) }} ha</td>
                        <td>{{ $clearance->generated_at?->timezone('Asia/Manila')->format('M d, Y h:i A') ?? 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4">No recent clearance outputs found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        <div>
            <div class="small">Prepared by:</div>
            <div class="signature-line">
                {{ $generatedBy?->name ?? 'System User' }}
            </div>
            <div class="small" style="text-align:center;">
                Authorized System User
            </div>
        </div>

        <div>
            <div class="small">Reviewed by:</div>
            <div class="signature-line">
                &nbsp;
            </div>
            <div class="small" style="text-align:center;">
                Authorized DAR Personnel
            </div>
        </div>
    </div>
</body>
</html>