<x-staff-shell
    title="Monitoring and Reports"
    subtitle="Generate administrative monitoring summaries for clearance applications, clearance outputs, location totals, and recent decisions."
    active="reports"
>
    <x-slot name="actions">
        <a href="{{ route('staff.reports.monitoring.print') }}" target="_blank" class="staff-button staff-button-primary">
            <i class="fa-solid fa-print"></i>
            Print / Save as PDF
        </a>
    </x-slot>

    <section class="staff-scope-banner">
        <div>
            <h3>Scope Notice</h3>
            <p>{{ $scopeNotice }}</p>
        </div>
        <span class="staff-scope-pill">Administrative Report</span>
    </section>

    <section class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div class="staff-panel staff-panel-pad">
            <p class="text-xs font-black uppercase tracking-wider text-gray-500">Total Applications</p>
            <p class="mt-3 font-heading text-3xl font-black text-gray-950">{{ number_format($totalApplications) }}</p>
            <p class="mt-2 text-sm text-gray-500">All encoded clearance applications.</p>
        </div>
        <div class="staff-panel staff-panel-pad">
            <p class="text-xs font-black uppercase tracking-wider text-gray-500">Pending Review</p>
            <p class="mt-3 font-heading text-3xl font-black text-amber-700">{{ number_format($statusCounts['pending_review'] ?? 0) }}</p>
            <p class="mt-2 text-sm text-gray-500">Applications awaiting staff action.</p>
        </div>
        <div class="staff-panel staff-panel-pad">
            <p class="text-xs font-black uppercase tracking-wider text-gray-500">Generated Clearances</p>
            <p class="mt-3 font-heading text-3xl font-black text-green-700">{{ number_format($totalClearances) }}</p>
            <p class="mt-2 text-sm text-gray-500">Clearance outputs generated by the system.</p>
        </div>
        <div class="staff-panel staff-panel-pad">
            <p class="text-xs font-black uppercase tracking-wider text-gray-500">Total Clearance Area</p>
            <p class="mt-3 font-heading text-3xl font-black text-gray-950">{{ number_format((float) $totalClearanceArea, 4) }}</p>
            <p class="mt-2 text-sm text-gray-500">Hectares recorded in generated clearances.</p>
        </div>
    </section>

    <section class="grid grid-cols-1 gap-5 xl:grid-cols-2">
        <div class="staff-panel staff-panel-pad">
            <h2 class="staff-panel-title">Application Status Breakdown</h2>
            <p class="staff-panel-subtitle">Current workflow count by application status.</p>
            <div class="mt-5 space-y-3">
                @forelse ($statusCounts as $status => $count)
                    <div class="flex items-center justify-between rounded-lg border border-gray-200 bg-gray-50 px-4 py-3">
                        <span class="font-semibold text-gray-700">{{ ucwords(str_replace('_', ' ', $status)) }}</span>
                        <span class="staff-badge {{ $status === 'approved' ? 'staff-badge-green' : ($status === 'not_approved' ? 'staff-badge-red' : ($status === 'pending_review' ? 'staff-badge-amber' : 'staff-badge-slate')) }}">{{ number_format($count) }}</span>
                    </div>
                @empty
                    <p class="text-sm text-gray-500">No application status data available.</p>
                @endforelse
            </div>
        </div>

        <div class="staff-panel staff-panel-pad">
            <h2 class="staff-panel-title">Municipality Breakdown</h2>
            <p class="staff-panel-subtitle">Applications grouped by recorded municipality.</p>
            <div class="mt-5 space-y-3">
                @forelse ($municipalityBreakdown as $row)
                    <div class="flex items-center justify-between rounded-lg border border-gray-200 bg-gray-50 px-4 py-3">
                        <span class="font-semibold text-gray-700">{{ $row->municipality }}</span>
                        <span class="staff-badge staff-badge-blue">{{ number_format($row->total) }}</span>
                    </div>
                @empty
                    <p class="text-sm text-gray-500">No municipality data available.</p>
                @endforelse
            </div>
        </div>
    </section>

    <section class="grid grid-cols-1 gap-5 xl:grid-cols-2">
        <div class="staff-panel overflow-hidden">
            <div class="staff-panel-pad">
                <h2 class="staff-panel-title">Recent Applications</h2>
                <p class="staff-panel-subtitle">Latest clearance applications included in monitoring.</p>
            </div>
            <div class="staff-table-wrap">
                <table class="staff-table">
                    <thead><tr><th>Code</th><th>Parties</th><th>Status</th><th>Location</th></tr></thead>
                    <tbody>
                        @forelse ($recentApplications as $application)
                            <tr>
                                <td><a href="{{ route('staff.applications.show', $application) }}" class="staff-link">{{ $application->application_code }}</a></td>
                                <td>
                                    <div>{{ $application->transferor_name }}</div>
                                    <div class="text-xs text-gray-500">To: {{ $application->transferee_name }}</div>
                                </td>
                                <td><span class="staff-badge">{{ ucwords(str_replace('_', ' ', $application->status)) }}</span></td>
                                <td>{{ $application->municipality ?? 'N/A' }}</td>
                            </tr>
                        @empty
                            <tr><td colspan="4" class="py-8 text-center text-gray-500">No recent applications.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>

        <div class="staff-panel overflow-hidden">
            <div class="staff-panel-pad">
                <h2 class="staff-panel-title">Recent Generated Clearances</h2>
                <p class="staff-panel-subtitle">Latest generated clearance outputs. These are not automatic ownership transfers.</p>
            </div>
            <div class="staff-table-wrap">
                <table class="staff-table">
                    <thead><tr><th>Clearance No.</th><th>Decision</th><th>Area</th><th>Generated</th></tr></thead>
                    <tbody>
                        @forelse ($recentClearances as $clearance)
                            <tr>
                                <td class="font-bold text-gray-900">{{ $clearance->clearance_number }}</td>
                                <td><span class="staff-badge {{ $clearance->decision_status === 'approved' ? 'staff-badge-green' : 'staff-badge-red' }}">{{ ucwords(str_replace('_', ' ', $clearance->decision_status)) }}</span></td>
                                <td>{{ number_format((float) $clearance->total_area_hectares, 4) }} ha</td>
                                <td>{{ $clearance->generated_at?->timezone('Asia/Manila')->format('M d, Y') ?? 'N/A' }}</td>
                            </tr>
                        @empty
                            <tr><td colspan="4" class="py-8 text-center text-gray-500">No generated clearances yet.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</x-staff-shell>
